export const zones = [
  { value: "akpakpa", label: "Akpakpa" },
  { value: "fidjrosse", label: "Fidjrossè" },
  { value: "calavi", label: "Calavi" },
  { value: "cotonou", label: "Cotonou" },
  { value: "porto-novo", label: "Porto-Novo" },
  { value: "parakou", label: "Parakou" },
];

export const suggestedSkills = [
  {
    group: "Construction et Bâtiment",
    items: [
      "Maçonnerie",
      "Carrelage",
      "Peinture",
      "Plâtrerie",
      "Façade",
      "Charpenterie",
      "Couvreur",
      "Ferraillage",
      "Travaux de bâtiment",
    ],
  },
  {
    group: "Électricité et Plomberie",
    items: [
      "Installation électrique",
      "Électricité",
      "Électricité bâtiment",
      "Électricité industrielle",
      "Plomberie",
      "Installation sanitaire",
      "Réparation de fuites",
      "Débouchage",
      "Chauffage",
      "Installation de climatisation",
    ],
  },
  {
    group: "Menuiserie et Ébénisterie",
    items: [
      "Menuiserie",
      "Ébénisterie",
      "Menuiserie agencement",
      "Menuiserie aluminium",
      "Menuiserie PVC",
      "Sculpture sur bois",
    ],
  },
  {
    group: "Métallurgie et Soudure",
    items: [
      "Soudure",
      "Serrurerie",
      "Ferronnerie",
      "Chaudronnerie",
      "Tôlerie",
      "Forge",
      "Soudure tuyauterie",
      "Serrurerie métallique",
    ],
  },
  {
    group: "Automobile et Mécanique",
    items: [
      "Mécanique",
      "Mécanique automobile",
      "Mécanique moto",
      "Carrosserie",
      "Peinture automobile",
      "Vulcanisation",
      "Électricité auto",
      "Réparation de freins",
      "Climatisation auto",
      "Remplacement de pièces",
    ],
  },
  {
    group: "Textile et Couture",
    items: [
      "Couture",
      "Retouche de vêtements",
      "Taille",
      "Modélisme",
      "Broderie",
      "Teinture",
      "Tissage",
      "Cordonnerie",
      "Maroquinerie",
    ],
  },
  {
    group: "Coiffure et Esthétique",
    items: [
      "Coiffure",
      "Manucure",
      "Pédicure",
      "Barbier",
      "Esthétique",
      "Tatouage",
      "Perruque",
    ],
  },
  {
    group: "Alimentation et Restauration",
    items: [
      "Cuisine",
      "Pâtisserie",
      "Boulangerie",
      "Boucherie",
      "Poissonnerie",
      "Traiteur",
      "Grillade",
    ],
  },
  {
    group: "Services et Transport",
    items: [
      "Transport",
      "Chauffeur",
      "Taxi",
      "Livraison",
      "Déménagement",
      "Portage",
    ],
  },
  {
    group: "Nettoyage et Entretien",
    items: [
      "Nettoyage",
      "Ménage",
      "Entretien",
      "Jardinage",
      "Paysagisme",
      "Élagage",
      "Nettoyage de vitres",
      "Nettoyage de façade",
    ],
  },
  {
    group: "Réparation et Maintenance",
    items: [
      "Réparation d'électroménager",
      "Réparation de téléphone",
      "Réparation d'ordinateur",
      "Réparation de TV",
      "Réparation de radio",
      "Réparation de vélo",
      "Réparation de moto",
      "Réparation de voiture",
      "Réparation de montre",
      "Réparation de parapluie",
    ],
  },
  {
    group: "Artisanat et Décoration",
    items: [
      "Poterie",
      "Céramique",
      "Sculpture",
      "Peinture artiste",
      "Décoration",
      "Tapisserie",
      "Encadrement",
      "Gravure",
      "Bijouterie",
      "Joaillerie",
      "Horlogerie",
    ],
  },
  {
    group: "Spécialités diverses",
    items: [
      "Vitrerie",
      "Miroiterie",
      "Parquet",
      "Sol",
      "Isolation phonique",
      "Étanchéité",
      "Piscine",
      "Désinsectisation",
      "Dératisation",
    ],
  },
  {
    group: "Services spécialisés",
    items: [
      "Photographie",
      "Vidéographie",
      "Design",
      "Impression",
      "Sérigraphie",
      "Gravure sur pierre",
      "Marbrerie",
      "Taille de pierre",
    ],
  },
];

export const ratingCriteria = [
  {
    id: 'price',
    label: '💸 Prix / Respect du devis',
    options: [
      { label: 'Devis respecté', points: 10 },
      { label: 'Petite différence', points: 6 },
      { label: 'Grande différence', points: 2 },
    ],
  },
  {
    id: 'deadlines',
    label: '⏱ Respect des délais',
    options: [
      { label: 'À temps', points: 10 },
      { label: 'Léger retard', points: 7 },
      { label: 'Retard important', points: 2 },
    ],
  },
  {
    id: 'professionalism',
    label: '🤝 Professionalisme',
    options: [
      { label: 'Très professionnel', points: 10 },
      { label: 'Assez professionnel', points: 5 },
      { label: 'Pas du tout professionnel', points: 0 },
    ],
  },
  {
    id: 'quality',
    label: '🛠 Qualité du travail',
    options: [
      { label: 'Finition excellente', points: 10 },
      { label: 'Correct', points: 7 },
      { label: 'Très basique', points: 4 },
      { label: 'Travail bâclé / précipité', points: 1 },
    ],
  },
  {
    id: 'communication',
    label: '📞 Communication',
    options: [
      { label: 'Excellente', points: 10 },
      { label: 'Moyenne', points: 6 },
      { label: 'Mauvaise', points: 2 },
    ],
  },
  
  // {
  //   id: 'cleanliness',
  //   label: '🧹 Propreté après travaux',
  //   options: [
  //     { label: 'Espace de travail propre', points: 10 },
  //     { label: 'Acceptable', points: 6 },
  //     { label: 'Sale', points: 2 },
  //   ],
  // },
];

export const professions = [
  // Construction et Bâtiment
  { value: "maçon", label: "Maçon" },
  { value: "carreleur", label: "Carreleur" },
  { value: "peintre", label: "Peintre" },
  { value: "plâtrier", label: "Plâtrier" },
  { value: "façadier", label: "Façadier" },
  { value: "charpentier", label: "Charpentier" },
  { value: "couvreur", label: "Couvreur" },
  { value: "ferrailleur", label: "Ferrailleur" },
  { value: "grutier", label: "Grutier" },
  { value: "travailleur-du-bâtiment", label: "Travailleur du bâtiment" },

  // Électricité et Plomberie
  { value: "électricien", label: "Électricien" },
  { value: "plombier", label: "Plombier" },
  { value: "installateur-sanitaire", label: "Installateur sanitaire" },
  { value: "chauffagiste", label: "Chauffagiste" },
  { value: "électricien-bâtiment", label: "Électricien bâtiment" },
  { value: "électricien-industriel", label: "Électricien industriel" },

  // Menuiserie et Ébénisterie
  { value: "menuisier", label: "Menuisier" },
  { value: "ébéniste", label: "Ébéniste" },
  { value: "menuisier-agenceur", label: "Menuisier agenceur" },
  { value: "menuisier-aluminium", label: "Menuisier aluminium" },
  { value: "menuisier-pvc", label: "Menuisier PVC" },
  { value: "sculpteur-sur-bois", label: "Sculpteur sur bois" },

  // Métallurgie et Soudure
  { value: "soudeur", label: "Soudeur" },
  { value: "serrurier", label: "Serrurier" },
  { value: "ferronnier", label: "Ferronnier" },
  { value: "chaudronnier", label: "Chaudronnier" },
  { value: "tôlier", label: "Tôlier" },
  { value: "forgeron", label: "Forgeron" },
  { value: "soudeur-tuyautier", label: "Soudeur tuyautier" },
  { value: "serrurier-métallier", label: "Serrurier métallier" },

  // Automobile et Mécanique
  { value: "mécanicien", label: "Mécanicien" },
  { value: "mécanicien-auto", label: "Mécanicien auto" },
  { value: "mécanicien-moto", label: "Mécanicien moto" },
  { value: "garagiste", label: "Garagiste" },
  { value: "carrossier", label: "Carrossier" },
  { value: "peintre-automobile", label: "Peintre automobile" },
  { value: "vulcanisateur", label: "Vulcanisateur" },
  { value: "électricien-auto", label: "Électricien auto" },
  { value: "réparateur-frein", label: "Réparateur de freins" },
  { value: "réparateur-climatisation-auto", label: "Réparateur climatisation auto" },

  // Textile et Couture
  { value: "couturier", label: "Couturier" },
  { value: "couturière", label: "Couturière" },
  { value: "tailleur", label: "Tailleur" },
  { value: "modéliste", label: "Modéliste" },
  { value: "brodeur", label: "Brodeur" },
  { value: "teinturier", label: "Teinturier" },
  { value: "tisserand", label: "Tisserand" },
  { value: "cordonnier", label: "Cordonnier" },
  { value: "maroquinier", label: "Maroquinier" },
  { value: "savetier", label: "Savetier" },

  // Coiffure et Esthétique
  { value: "coiffeur", label: "Coiffeur" },
  { value: "coiffeuse", label: "Coiffeuse" },
  { value: "barbier", label: "Barbier" },
  { value: "esthéticienne", label: "Esthéticienne" },
  { value: "manucure", label: "Manucure" },
  { value: "pédicure", label: "Pédicure" },
  { value: "tatoueur", label: "Tatoueur" },
  { value: "perruquier", label: "Perruquier" },

  // Alimentation et Restauration
  { value: "cuisinier", label: "Cuisinier" },
  { value: "cuisinière", label: "Cuisinière" },
  { value: "boulanger", label: "Boulanger" },
  { value: "pâtissier", label: "Pâtissier" },
  { value: "boucher", label: "Boucher" },
  { value: "poissonnier", label: "Poissonnier" },
  { value: "traiteur", label: "Traiteur" },
  { value: "grilladeur", label: "Grilladeur" },
  { value: "vendeur-de-nourriture", label: "Vendeur de nourriture" },

  // Services et Transport
  { value: "chauffeur", label: "Chauffeur" },
  { value: "chauffeur-taxi", label: "Chauffeur taxi" },
  { value: "chauffeur-livreur", label: "Chauffeur livreur" },
  { value: "chauffeur-moto", label: "Chauffeur moto" },
  { value: "porteur", label: "Porteur" },
  { value: "déménageur", label: "Déménageur" },

  // Nettoyage et Entretien
  { value: "nettoyeur", label: "Nettoyeur" },
  { value: "femme-de-ménage", label: "Femme de ménage" },
  { value: "agent-d-entretien", label: "Agent d'entretien" },
  { value: "jardinier", label: "Jardinier" },
  { value: "paysagiste", label: "Paysagiste" },
  { value: "élagueur", label: "Élagueur" },
  { value: "nettoyeur-de-vitres", label: "Nettoyeur de vitres" },

  // Réparation et Maintenance
  { value: "réparateur-électroménager", label: "Réparateur électroménager" },
  { value: "réparateur-téléphone", label: "Réparateur téléphone" },
  { value: "réparateur-ordinateur", label: "Réparateur ordinateur" },
  { value: "réparateur-tv", label: "Réparateur TV" },
  { value: "réparateur-radio", label: "Réparateur radio" },
  { value: "réparateur-bicyclette", label: "Réparateur de bicyclettes" },
  { value: "réparateur-montre", label: "Réparateur de montres" },
  { value: "réparateur-parapluie", label: "Réparateur de parapluies" },

  // Artisanat et Décoration
  { value: "potier", label: "Potier" },
  { value: "céramiste", label: "Céramiste" },
  { value: "sculpteur", label: "Sculpteur" },
  { value: "peintre-artiste", label: "Peintre artiste" },
  { value: "décorateur", label: "Décorateur" },
  { value: "tapissier", label: "Tapissier" },
  { value: "encadreur", label: "Encadreur" },
  { value: "graveur", label: "Graveur" },
  { value: "bijoutier", label: "Bijoutier" },
  { value: "joaillier", label: "Joaillier" },
  { value: "horloger", label: "Horloger" },

  // Spécialités diverses
  { value: "vitrier", label: "Vitrier" },
  { value: "miroitier", label: "Miroitier" },
  { value: "parqueteur", label: "Parqueteur" },
  { value: "solier", label: "Solier" },
  { value: "isolation-phonique", label: "Spécialiste en isolation phonique" },
  { value: "étancheur", label: "Étancheur" },
  { value: "piscinier", label: "Piscinier" },
  { value: "pompier", label: "Pompier" },
  { value: "désinsectiseur", label: "Désinsectiseur" },
  { value: "dératiseur", label: "Dératiseur" },
  { value: "nettoyeur-de-façade", label: "Nettoyeur de façade" },

  // Artisanat traditionnel
  { value: "tisserand-traditionnel", label: "Tisserand traditionnel" },
  { value: "potier-traditionnel", label: "Potier traditionnel" },
  { value: "sculpteur-traditionnel", label: "Sculpteur traditionnel" },
  { value: "forgeron-traditionnel", label: "Forgeron traditionnel" },
  { value: "tannage", label: "Tanneur" },
  { value: "vannerie", label: "Vannier" },

  // Services spécialisés
  { value: "photographe", label: "Photographe" },
  { value: "vidéaste", label: "Vidéaste" },
  { value: "imprimeur", label: "Imprimeur" },
  { value: "sérigraphe", label: "Sérigraphe" },
  { value: "graveur-sur-pierre", label: "Graveur sur pierre" },
  { value: "marbreur", label: "Marbreur" },
  { value: "tailleur-de-pierre", label: "Tailleur de pierre" },
];